stages:
  - version
  - build
  - package
  - deploy

.shared_windows_runners:
  before_script:
    - git clone $Env:GIT_URL
    - mv mdf-resources\resources resources
    - mv -Force mdf-resources\product.json product.json
  tags:
    - shared-windows
    - windows
    - windows-1809
  only:
    - master
    - tags

build:
  extends:
    - .shared_windows_runners
  stage: build
  script:
    - echo "$Env:CI_PROJECT_DIR"
    - Invoke-WebRequest -Uri https://www.python.org/ftp/python/3.7.7/python-3.7.7-amd64.exe -OutFile python-3.7.7-amd64.exe
    - dir
    - Start-Process -FilePath "python-3.7.7-amd64.exe" -ArgumentList "/quiet Include_test=0 Shortcuts=0" -Wait
    - dir $Env:LOCALAPPDATA\Programs\Python
    - $Env:Path += ";$Env:LOCALAPPDATA\Programs\Python\Python37\"
    - $Env:Path += ";$Env:LOCALAPPDATA\Programs\Python\Python37\Scripts\"
    - python -m pip install --upgrade pip
    - python -V
    - pip install -r requirements.txt
    - mkdir build
    - cd src
    - pyinstaller main.spec
    - pyinstaller msu.spec
    - mv -Force dist\msu dist\main
    - mv dist\main $Env:CI_PROJECT_DIR\build\app
  artifacts:
    expire_in: 1h
    paths:
    - build\

versioning:
  image: python:latest
  stage: version
  before_script:
    - git clone $GIT_URL
    - mv mdf-resources/resources/app/LICENSE public/
    - mv mdf-resources/resources/app/OpenSourceLicense.txt public/
    - mv -f mdf-resources/product.json product.json
  script:
    - pip install requests
    - python package/vc.py -r
  artifacts:
    expire_in: 3h
    paths:
      - public/
      - output/
      - src/version_info.txt
      - package/info/
  only:
    - master
    - tags

pre-release:
  extends:
    - .shared_windows_runners
  stage: package
  script:
    - $ver=cat output/last_version.txt
    - mv -Force resources\app\LICENSE LICENSE
    - choco install nsis -y
    - $Env:Path += ";C:\Program Files (x86)\NSIS\"
    - makensis.exe /INPUTCHARSET UTF8 /DPRODUCT_VERSION=$ver "/DPRODUCT_NAME=Mulgyeol Distance Fetcher" "/DOUTFILE_NAME=MDFSetup-beta.exe" "/DEXE_NAME=MDF.exe" package\MDF.nsi
    - mv package\MDFSetup-beta.exe .\
  artifacts:
    name: "MDFSetup-beta"
    expire_in: 1 week
    paths:
    - .\*.exe
  only:
    - master

stable-release:
  extends:
    - .shared_windows_runners
  stage: package
  script:
    - $ver=cat output/last_version.txt
    - mv -Force resources\app\LICENSE LICENSE
    - choco install nsis -y
    - $Env:Path += ";C:\Program Files (x86)\NSIS\"
    - makensis.exe /INPUTCHARSET UTF8 /DPRODUCT_VERSION=$ver "/DPRODUCT_NAME=Mulgyeol Distance Fetcher" "/DOUTFILE_NAME=MDFSetup-stable.exe" "/DEXE_NAME=MDF.exe" package\MDF.nsi
    - mv package\MDFSetup-stable.exe .\
  artifacts:
    name: "MDFSetup-stable"
    expire_in: 2 yrs
    paths:
    - .\*.exe
  only:
    - tags
    
pages:
  stage: deploy
  script:
    - echo "pages"
  artifacts:
    paths:
      - public
  only:
    - master
    - tags