from PyQt5 import QtCore, QtGui, QtWidgets

class setting_dialog(QtCore.QObject):

    def setupUi(self, dialog):
        super().__init__()
        dialog.setObjectName('dialog')
        dialog.setFixedSize(417, 344)
        # dialog.setSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        self.title = QtWidgets.QLabel(dialog)
        self.title.setGeometry(QtCore.QRect(20, 20, 201, 16))
        font = QtGui.QFont()
        font.setFamily('맑은 고딕')
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.title.setMouseTracking(False)
        self.title.setObjectName('title')
        self.widget = QtWidgets.QWidget(dialog)
        self.widget.setGeometry(QtCore.QRect(240, 300, 158, 25))
        self.widget.setObjectName('widget')
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName('horizontalLayout_5')
        font = QtGui.QFont()
        font.setFamily('맑은 고딕')
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName('pushButton')
        self.pushButton.setFont(font)
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName('pushButton_2')
        self.pushButton_2.setFont(font)
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.widget1 = QtWidgets.QWidget(dialog)
        self.widget1.setGeometry(QtCore.QRect(20, 50, 381, 241))
        self.widget1.setObjectName('widget1')
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName('gridLayout_2')
        self.groupBox = QtWidgets.QGroupBox(self.widget1)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName('groupBox')
        self.widget2 = QtWidgets.QWidget(self.groupBox)
        self.widget2.setGeometry(QtCore.QRect(13, 21, 317, 81))
        self.widget2.setObjectName('widget2')
        self.gridLayout = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName('gridLayout')
        self.subtitle_platform = QtWidgets.QLabel(self.widget2)
        self.subtitle_platform.setObjectName('subtitle_platform')
        self.gridLayout.addWidget(self.subtitle_platform, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName('horizontalLayout_3')
        self.radioButton_naver = QtWidgets.QRadioButton(self.widget2)
        self.radioButton_naver.setObjectName('radioButton_naver')
        self.horizontalLayout_3.addWidget(self.radioButton_naver)
        self.radioButton_2_kakao = QtWidgets.QRadioButton(self.widget2)
        self.radioButton_2_kakao.setObjectName('radioButton_2_kakao')
        self.horizontalLayout_3.addWidget(self.radioButton_2_kakao)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.subtitle_waittime = QtWidgets.QLabel(self.widget2)
        self.subtitle_waittime.setObjectName('subtitle_waittime')
        self.gridLayout.addWidget(self.subtitle_waittime, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName('horizontalLayout_2')
        self.waittime_start = QtWidgets.QSpinBox(self.widget2)
        self.waittime_start.setObjectName('waittime_start')
        self.horizontalLayout_2.addWidget(self.waittime_start)
        self.label_2 = QtWidgets.QLabel(self.widget2)
        self.label_2.setObjectName('label_2')
        self.horizontalLayout_2.addWidget(self.label_2)
        self.waittime_end = QtWidgets.QSpinBox(self.widget2)
        self.waittime_end.setObjectName('waittime_end')
        self.horizontalLayout_2.addWidget(self.waittime_end)
        self.label_8 = QtWidgets.QLabel(self.widget2)
        self.label_8.setObjectName('label_8')
        self.horizontalLayout_2.addWidget(self.label_8)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.waittime_item = QtWidgets.QSpinBox(self.widget2)
        self.waittime_item.setObjectName('waittime_item')
        self.waittime_item.setMinimum(1)
        self.horizontalLayout.addWidget(self.waittime_item)
        self.label_3 = QtWidgets.QLabel(self.widget2)
        self.label_3.setObjectName('label_3')
        self.horizontalLayout.addWidget(self.label_3)
        self.waittime_item_sec = QtWidgets.QSpinBox(self.widget2)
        self.waittime_item_sec.setObjectName('waittime_item_sec')
        self.horizontalLayout.addWidget(self.waittime_item_sec)
        self.label_4 = QtWidgets.QLabel(self.widget2)
        self.label_4.setObjectName('label_4')
        self.horizontalLayout.addWidget(self.label_4)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget1)
        font = QtGui.QFont()
        font.setFamily('맑은 고딕')
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName('groupBox_2')
        self.widget3 = QtWidgets.QWidget(self.groupBox_2)
        self.widget3.setGeometry(QtCore.QRect(10, 20, 362, 81))
        self.widget3.setObjectName('widget3')
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName('verticalLayout')
        self.subtitle_networkerror = QtWidgets.QLabel(self.widget3)
        self.subtitle_networkerror.setObjectName('subtitle_networkerror')
        self.verticalLayout.addWidget(self.subtitle_networkerror)
        self.radioButton_finish = QtWidgets.QRadioButton(self.widget3)
        self.radioButton_finish.setObjectName('radioButton_finish')
        self.verticalLayout.addWidget(self.radioButton_finish)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName('horizontalLayout_4')
        self.radioButton_wait_again = QtWidgets.QRadioButton(self.widget3)
        self.radioButton_wait_again.setObjectName('radioButton_wait_again')
        self.horizontalLayout_4.addWidget(self.radioButton_wait_again)
        self.wait_again_min = QtWidgets.QSpinBox(self.widget3)
        self.wait_again_min.setMinimum(1)
        self.wait_again_min.setObjectName('wait_again_min')
        self.horizontalLayout_4.addWidget(self.wait_again_min)
        self.label_7 = QtWidgets.QLabel(self.widget3)
        self.label_7.setObjectName('label_7')
        self.horizontalLayout_4.addWidget(self.label_7)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate('dialog', '설정'))
        self.title.setText(_translate('dialog', 'Mulgyeol Distance Fetcher 설정'))
        self.pushButton.setText(_translate('dialog', '확인'))
        self.pushButton_2.setText(_translate('dialog', '취소'))
        self.groupBox.setTitle(_translate('dialog', '기본 설정'))
        self.subtitle_platform.setText(_translate('dialog', '플랫폼:'))
        self.radioButton_naver.setText(_translate('dialog', '네이버 지도'))
        self.radioButton_2_kakao.setText(_translate('dialog', '카카오 지도'))
        self.subtitle_waittime.setText(_translate('dialog', '대기 시간:'))
        self.label_2.setText(_translate('dialog', '초 ~'))
        self.label_8.setText(_translate('dialog', '초 사이의 난수            '))
        self.label_3.setText(_translate('dialog', '개 항목 수집 후'))
        self.label_4.setText(_translate('dialog', '분 추가 대기'))
        self.groupBox_2.setTitle(_translate('dialog', '오류 처리'))
        self.subtitle_networkerror.setText(_translate('dialog', '네트워크 오류 발생 시'))
        self.radioButton_finish.setText(_translate('dialog', '정보 수집을 마칩니다.'))
        self.radioButton_wait_again.setText(_translate('dialog', '설정된 시간 동안 대기한 후 다시 시도합니다.'))
        self.label_7.setText(_translate('dialog', '분 대기'))


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog = QtWidgets.QDialog()
    ui = setting_dialog()
    ui.setupUi(dialog)
    dialog.show()
    sys.exit(app.exec_())